import type { Metadata } from "next";
import { Tangerine } from 'next/font/google';
import "./globals.css";
import Header from "./_components/Header/Header";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const FontTangerine = Tangerine({
    weight: "400",
    subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" className={FontTangerine.className}>
      <body>
        <Header />
        <main>
          {children}
          </main>
        </body>
    </html>
  );
}
