import type { Metadata } from "next";
import { Tangerine } from 'next/font/google';
import { Cinzel } from 'next/font/google';
import "./globals.css";
import Header from "./_components/Header/Header";
import Footer from "./_components/Footer/Footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const FontTangerine = Tangerine({
  weight: ["400", "700"],
  subsets: ["latin"],
});

const FontCinzel = Cinzel({
  weight: ["400"],
  subsets: ["latin"],
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <Header />
        <main>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
